### PR TITLE
Merge request

### PR DESCRIPTION
**Pull request by patging**
Requesting merge

### CODE REVIEW

**Comment by patging** [comment]
Hey Paulina! Hope you're well!

Just requesting this merge. Does this work for you on your pc?

Best regards
Patrick

**Comment by thebaolin** [comment]
Hey Patrick!

This works for me on my PC. Does it work on your PC?

Thanks.

**Comment by patging** [comment]
Let me check for you....

Ok so it works on my Macbook and only works on my windows computer if you add the flag -std=C++11.

Hope that helps.
PG

**Comment by patging** [comment]
Great thanks so much Paulina! Have a great holiday! Enjoy Paris!

**Comment by thebaolin** [comment]
Done merging!

Thanks, and have a wonderful time in Ireland!! Bring back some souvenirs :)

**Comment by patging** [comment]
Hey Paulina! Hope you're well!

As you know, I'm a Computer Science major not an English major. So I made a mistake by operating on your repository for the last two weeks! My apologies for any damage I caused.

On the bright side i made your repo better :) !

Still, best regards and enjoy your holiday!
Patrick Ging

**Pull request merged**
